### ISSUE TITLE
Opensea Listing tapp does not display the images of the token.

### ISSUE THREAD

**Issue by abhishes007** [TokenScript-Framework/tapp-recipes#2]
Opensea Listing tapp does not display the images of the token.

Steps:
1. Visit opensea and create a listing.
2. Go to opensea listing tap and observe the image shown.
3. Share the link on X and observe the image shown.

Issue:
1. We could show the listed token image instead of using the default OpenSea image currently being shown.

Screenshots:

OpenSea Listing Tapp:
<img width="1166" alt="image" src="https://github.com/user-attachments/assets/104d56dd-9464-45ac-b938-e99b201d5d9d">

Shared on X:
<img width="1165" alt="image" src="https://github.com/user-attachments/assets/4eea655b-ee83-41fa-b466-18a5dfb5b13c">

**Comment by huweihong** [comment]
I checked the contract of this nft. It is not a standard ERC721 contract. So the code can't detect its type and get the metadata from it. cc @foxgem

**Comment by abhishes007** [comment]
Verified that image is shown for normal token (checked on sepolia)

Tapp Image:
![image](https://github.com/user-attachments/assets/a80b9ff8-6c18-460c-a111-654961077bd1)


On X:
![image](https://github.com/user-attachments/assets/561dfacf-93ae-4dd7-84f6-859dc00068f8)

Marking the issue as closed.
